import { CheckCircle2, RotateCcw, Save, Trash2, X } from 'lucide-react'
import { useState } from 'react'
import type { GroupSummary, TaskDetail } from '../lib/api'
import type { TaskDetailDraft } from '../lib/taskFormModel'
import { TaskFormFields } from './TaskFormFields'

type Props = { task?: TaskDetail; draft: TaskDetailDraft | null; groups: GroupSummary[]; isLoading: boolean; error: unknown; isEditable: boolean; isBusy: boolean; saveError: string | null; newSubtaskTitle: string; onDraftChange: (updater: (draft: TaskDetailDraft) => TaskDetailDraft) => void; onNewSubtaskTitleChange: (title: string) => void; onClose: () => void; onSave: () => void; onCreateSubtask: () => void; onDeleteSubtask: (id: string) => void; onComplete?: () => void; onRestore?: () => void; onDelete?: () => void; friendlyError: (error: unknown, fallback: string) => string }

function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${value}T12:00:00`)) : 'No due date' }
function formatDateTime(value: string | null) { if (!value) return 'No reminder'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'No reminder' : new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(date) }
function MetadataTile({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-[1.2rem] bg-black/20 p-3"><p className="text-[0.62rem] font-semibold uppercase tracking-[0.15em] text-on-surface-variant">{label}</p><p className="mt-2 truncate text-sm font-medium text-on-surface">{value}</p></div> }

function PreviewHeader({ task, onClose }: { task?: TaskDetail; onClose: () => void }) {
  return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4 p-5 pb-3 sm:p-6"><div className="min-w-0 space-y-2"><div className="flex flex-wrap items-center gap-2"><span className="rounded-pill bg-white/6 px-3 py-1 text-[0.62rem] font-semibold uppercase tracking-[0.16em] text-on-surface-variant">Task preview</span>{task ? <><span className="rounded-pill bg-surface-container-high px-3 py-1 text-[0.62rem] font-semibold uppercase tracking-[0.16em] text-on-surface-variant">{task.status === 'completed' ? 'Completed' : 'Open'}</span><span className="max-w-[12rem] truncate rounded-pill bg-surface-container-high px-3 py-1 text-[0.62rem] font-semibold uppercase tracking-[0.16em] text-on-surface-variant">{task.group.name}</span>{task.needs_review ? <span className="rounded-pill bg-warning/20 px-3 py-1 text-[0.62rem] font-semibold uppercase tracking-[0.16em] text-warning">Needs review</span> : null}</> : null}</div><h2 id="task-preview-title" className="font-display text-2xl leading-tight text-on-surface sm:text-3xl">{task?.title ?? 'Loading task'}</h2></div><button type="button" onClick={onClose} className="flex h-10 w-10 items-center justify-center rounded-full bg-white/8 text-on-surface-variant" aria-label="Close task preview"><X className="h-4 w-4" /></button></div>
}

function EditableTask({ draft, groups, disabled, onChange }: { draft: TaskDetailDraft; groups: GroupSummary[]; disabled: boolean; onChange: Props['onDraftChange'] }) {
  const [isGroupDropdownOpen, setIsGroupDropdownOpen] = useState(false)
  return <TaskFormFields {...draft} groups={groups} isGroupDropdownOpen={isGroupDropdownOpen} disabled={disabled} onTitleChange={(title) => onChange((current) => ({ ...current, title }))} onDescriptionChange={(description) => onChange((current) => ({ ...current, description }))} onGroupIdChange={(groupId) => onChange((current) => ({ ...current, groupId }))} onDueDateChange={(dueDate) => onChange((current) => ({ ...current, dueDate }))} onReminderAtChange={(reminderAt) => onChange((current) => ({ ...current, reminderAt }))} onRecurrenceChange={(recurrence) => onChange((current) => ({ ...current, recurrence }))} onGroupDropdownOpenChange={setIsGroupDropdownOpen} />
}

function ReadOnlyTask({ task }: { task: TaskDetail }) {
  const recurrence = task.recurrence_frequency ? task.recurrence_frequency[0].toUpperCase() + task.recurrence_frequency.slice(1) : 'One-off'
  return <><div className="grid gap-3 sm:grid-cols-2"><MetadataTile label="Due date" value={formatDate(task.due_date)} /><MetadataTile label="Reminder" value={formatDateTime(task.reminder_at)} /><MetadataTile label="Recurrence" value={recurrence} /><MetadataTile label="Subtasks" value={`${task.subtasks.length} subtasks`} /></div><section className="rounded-[1.25rem] bg-surface/45 p-4"><p className="text-[0.65rem] font-semibold uppercase tracking-[0.15em] text-on-surface-variant">Context</p><p className="mt-3 text-sm leading-6 text-on-surface-variant">{task.description || 'No description yet.'}</p></section></>
}

function Checklist({ task, editable, busy, title, onTitleChange, onCreate, onDelete }: { task: TaskDetail; editable: boolean; busy: boolean; title: string; onTitleChange: (value: string) => void; onCreate: () => void; onDelete: (id: string) => void }) {
  return <section className="rounded-[1.25rem] bg-surface-container/90 p-4 shadow-ambient"><div className="flex items-center justify-between"><div><p className="font-display text-lg text-on-surface">Checklist</p><p className="mt-1 text-xs text-on-surface-variant">{task.subtasks.length} subtasks</p></div><span className="rounded-pill bg-surface-container-high px-3 py-1 text-[0.68rem] uppercase text-on-surface-variant">{task.subtasks.filter((item) => item.is_completed).length} done</span></div><div className="mt-3 space-y-2">{task.subtasks.length ? task.subtasks.map((subtask) => <div key={subtask.id} className="flex items-start gap-3 rounded-card bg-surface-dim p-3"><span className={`mt-0.5 h-4 w-4 rounded-pill ${subtask.is_completed ? 'bg-primary' : 'bg-surface-container-high ring-1 ring-white/15'}`} /><p className={`min-w-0 flex-1 text-sm ${subtask.is_completed ? 'text-on-surface-variant line-through' : 'text-on-surface'}`}>{subtask.title}</p>{editable ? <button type="button" onClick={() => onDelete(subtask.id)} disabled={busy} aria-label={`Delete ${subtask.title}`}><Trash2 className="h-4 w-4" /></button> : null}</div>) : <div className="rounded-card bg-surface-dim px-4 py-4 text-sm text-on-surface-variant">No subtasks yet.</div>}</div>{editable ? <div className="mt-3 flex gap-2"><input value={title} onChange={(event) => onTitleChange(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && title.trim()) onCreate() }} className="min-w-0 flex-1 rounded-card bg-surface-dim px-3 py-3 text-sm text-on-surface" placeholder="Add a subtask..." disabled={busy} /><button type="button" onClick={onCreate} disabled={!title.trim() || busy} className="rounded-pill bg-primary px-4 py-2 text-sm font-semibold text-surface disabled:opacity-50">Add</button></div> : null}</section>
}

type PreviewBodyProps = { task?: TaskDetail; draft: TaskDetailDraft | null; groups: GroupSummary[]; isLoading: boolean; error: unknown; isEditable: boolean; isBusy: boolean; saveError: string | null; newSubtaskTitle: string; onDraftChange: Props['onDraftChange']; onNewSubtaskTitleChange: (title: string) => void; onCreateSubtask: () => void; onDeleteSubtask: (id: string) => void; friendlyError: Props['friendlyError'] }
function PreviewBody(props: PreviewBodyProps) {
  if (props.isLoading) return <div className="h-40 animate-pulse rounded-card bg-surface-container-high" aria-busy="true" />
  if (props.error) return <div className="rounded-card bg-[rgba(80,18,18,0.92)] p-4 text-sm text-red-100">{props.friendlyError(props.error, 'Task preview could not be loaded.')}</div>
  if (!props.task) return null
  return <div className="space-y-4">{props.isEditable && props.draft ? <EditableTask draft={props.draft} groups={props.groups} disabled={props.isBusy} onChange={props.onDraftChange} /> : <ReadOnlyTask task={props.task} />}{props.saveError ? <p className="rounded-xl bg-error/15 px-3 py-2 text-sm text-error">{props.saveError}</p> : null}<Checklist task={props.task} editable={props.isEditable} busy={props.isBusy} title={props.newSubtaskTitle} onTitleChange={props.onNewSubtaskTitleChange} onCreate={props.onCreateSubtask} onDelete={props.onDeleteSubtask} /></div>
}

function PreviewFooter({ task, editable, busy, canSave, onClose, onSave, onComplete, onRestore, onDelete }: { task?: TaskDetail; editable: boolean; busy: boolean; canSave: boolean; onClose: () => void; onSave: () => void; onComplete?: () => void; onRestore?: () => void; onDelete?: () => void }) {
  return <div className="border-t border-white/10 bg-[rgba(20,20,20,0.86)] p-3"><div className="flex items-center gap-2"><button type="button" onClick={onClose} className="min-h-11 flex-1 rounded-pill bg-white/5 px-4 py-2.5 text-sm text-on-surface">Close</button><div className="ml-auto flex items-center gap-2">{task?.status === 'open' && onComplete ? <button type="button" onClick={onComplete} disabled={busy} aria-label="Complete" className="h-11 w-11 rounded-full bg-success/20 text-success"><CheckCircle2 className="m-auto h-4 w-4" /></button> : null}{task?.status === 'completed' && onRestore ? <button type="button" onClick={onRestore} disabled={busy} className="rounded-pill bg-surface-container-high px-4 py-3 text-sm"><RotateCcw className="mr-2 inline h-4 w-4" />Restore</button> : null}{onDelete ? <button type="button" onClick={onDelete} disabled={busy} aria-label="Delete task"><Trash2 className="h-4 w-4 text-tertiary" /></button> : null}{editable ? <button type="button" onClick={onSave} disabled={busy || !canSave} aria-label="Save changes" className="h-11 w-11 rounded-full bg-primary text-surface disabled:opacity-50"><Save className="m-auto h-4 w-4" /></button> : null}</div></div></div>
}

export function TaskPreviewView(props: Props) {
  return <div className="fixed inset-0 z-[120] flex items-end justify-center bg-black/65 p-3 backdrop-blur-md sm:items-center" role="dialog" aria-modal="true" aria-labelledby="task-preview-title" onMouseDown={(event) => { if (event.target === event.currentTarget) props.onClose() }}><div className="max-h-[92dvh] w-full max-w-2xl overflow-hidden rounded-[1.7rem] bg-[radial-gradient(circle_at_top_left,_rgba(186,158,255,0.18),_rgba(32,32,31,0.98)_42%,_rgba(14,14,14,1)_100%)] shadow-[0_28px_80px_rgba(0,0,0,0.62)]"><div className="flex max-h-[92dvh] flex-col"><PreviewHeader task={props.task} onClose={props.onClose} /><div className="min-h-0 flex-1 overflow-y-auto px-5 pb-4 sm:px-6"><PreviewBody task={props.task} draft={props.draft} groups={props.groups} isLoading={props.isLoading} error={props.error} isEditable={props.isEditable} isBusy={props.isBusy} saveError={props.saveError} newSubtaskTitle={props.newSubtaskTitle} onDraftChange={props.onDraftChange} onNewSubtaskTitleChange={props.onNewSubtaskTitleChange} onCreateSubtask={props.onCreateSubtask} onDeleteSubtask={props.onDeleteSubtask} friendlyError={props.friendlyError} /></div><PreviewFooter task={props.task} editable={props.isEditable} busy={props.isBusy} canSave={Boolean(props.draft?.title.trim())} onClose={props.onClose} onSave={props.onSave} onComplete={props.onComplete} onRestore={props.onRestore} onDelete={props.onDelete} /></div></div></div>
}
